baseURL: https://netwithalex.blog
defaultContentLanguage: en
languageCode: en-US
title: NetWithAlex
Description: A technical blog about SD-WAN, automation, and modern networking. Learn, explore, and dive deep into network solutions with practical examples.
theme: 
  - plausible-hugo
  - PaperMod
taxonomies:
  category: category
  tag: tag
params:
  homeInfoParams:
    title: "Hey, I'm Alex ğŸ‘‹"
    content: >
      NetWithAlex is my space on the web where I share my passion for networking and technology ğŸš€. 
      Here you'll find interesting and useful resources explained in a simple way to help you learn clearly and practically.<br><br>
      ğŸ’¬ Do you have questions or ideas? Feel free to reach outâ€”Iâ€™d like to hear from you!
  plausible:
    enable: true
    domain: netwithalex.blog
    gitstar: false
  socialIcons: 
    - name: Linkedin
      url: "https://www.linkedin.com/in/alexruizs/"
    - name: "email"
      url: "mailto:netwithalex@gmail.com"
  env: production
  defaultTheme: auto
  disableThemeToggle: false
  showShareButtons: false
  showReadingTime: true
  showToc: true
  tocOpen: true
  showBreadCrumbs: true
  showCodeCopyButtons: true
  comments: true
  hideFooter: false
  assets:
    favicon: "/assets/favicon.ico"
    disableHLJS: true
markup:
  highlight:
    codeFences: true
    guessSyntax: true
    style: monokai
  goldmark:
    renderer:
      unsafe: true
outputs:
  home:
    - HTML
    - RSS
    - JSON
outputFormats:
  RSS:
    mediaType: application/rss+xml
    baseName: feed

languages:
  en:
    languageName: "English"
    weight: 1
    contentDir: "content/en"
    menu:
      main:
        - name: Home
          url: /
          weight: 1
        - name: Archive
          url: /archives/
          weight: 2
        - name: Categories
          url: /category/
          weight: 3
        - name: About me.
          url: /about/
          weight: 4
        - name: "ğŸ”"
          url: /search/
          weight: 5

  es:
    languageName: "EspaÃ±ol"
    weight: 2
    contentDir: "content/es"
    menu:
      main:
        - name: Inicio
          url: /es/
          weight: 1
        - name: Archivo
          url: /es/archives/
          weight: 2
        - name: CategorÃ­as
          url: /es/category/
          weight: 3
        - name: Sobre mÃ­
          url: /es/sobre-mi/
          weight: 4
        - name: "ğŸ”"
          url: /es/search/
          weight: 5
    params:
      homeInfoParams:
        title: "Hola, soy Alex ğŸ‘‹"
        content: >
          NetWithAlex es mi espacio en la web donde comparto mi pasiÃ³n por las redes y la tecnologÃ­a ğŸš€. 
          AquÃ­ encontrarÃ¡s recursos interesantes y Ãºtiles explicados de manera sencilla para ayudarte a aprender de forma clara y prÃ¡ctica.<br><br>
          ğŸ’¬ Â¿Tienes preguntas o ideas? Â¡No dudes en escribirme, me gustarÃ­a saber de ti!
